# Generated by Django 5.2.8 on 2025-12-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breed",
            options={"verbose_name": "Порода", "verbose_name_plural": "Породы"},
        ),
    ]
